{
  currentUser {
    id
    identifier
    password
    name
    city {
      id
      name
      available
      votes
    }
    roles {
      name
      claims {
        id
        name
      }
    }
  }
}
