query offers($category: String!) {
  offers(category: $category) {
    id
    name
    price
    image
    description
    availabilityStarts
    price
    priceCurrency
    count
    category
    benefit
    votesNeeded
  }
}
